### ISSUE TITLE
merge changes we did to our private copy here

### ISSUE THREAD

**Issue by felixhirt** [ita-ch/secs4net#1]
did we already make some changes on our local copy? we should merge them here and use this as base for further development

**Comment by JulienDespond** [comment]
Is forking the best way to go? And is the fork private (ita-ch) or public?

**Comment by felixhirt** [comment]
the fork is public. i thought it would be the best way to go? if we want to keep our changes to ourselves, we would have to mirror the repo on github as well (there are not private forks of public repos). In this case, we could stick with bitbucket i guess...

I dont think making these changes in the open would be detrimental to us? Maybe we can even propose to merge generally applicable changes we plan to make (like saving commands in json) back to the master version. Open source and whatnot!
