### ISSUE TITLE
Prepare publishing

### ISSUE THREAD

**Issue by felixhirt** [ita-ch/secs4net#2]
Find a way to publish. Do we use github packages/actions or build it locally and put it on our nuget server?

**Comment by JulienDespond** [comment]
For now, it's on our server. 
Makes sense to keep it there as we are using our ILmerge packet.

**Comment by felixhirt** [comment]
ah yes, so we need our internal nuget stream anyway to build it. We will keep it local then. Maybe one day, our custom build targets will be here on github as well ...
